import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Club {

    // the primary key (ID) is auto generated by ObjectDB
    // we can use this our permanent token
    @Id 
    @GeneratedValue 
    private Long id;
    
    private String clubName;
    private String contactEmail = "";
    private String description;

    private float[] embeddings;
    private List<String> keywords;

    // a no argument constructor is required by JPA
    public Club() {
    }

    public Club(String clubName, String contactEmail, String description) {
        this.clubName = clubName.trim();
        this.contactEmail = contactEmail.trim();
        this.description = description.trim();
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public String getName() {
        return clubName;
    }

    public String getEmail() {
        return contactEmail;
    }

    public void setName(String clubName) {
        this.clubName = clubName.trim();
    }

    public void setDescription(String description) {
        this.description = description.trim();
    }
}